name: jpstockmemo2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.0
  path: ^1.8.2
  flutter_staggered_grid_view: ^0.6.2
  provider: ^6.0.5
  sqflite: ^2.2.2
  intl: ^0.18.0
  google_mobile_ads: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.2.0+1
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
